language: cpp

matrix:
    include:
        - os: osx
          osx_image: xcode9.2
          compiler: clang

install:
    - cd ..
    - git clone https://github.com/chibidev/git-dependencies.git
    - export PATH=$PATH:`pwd`/git-dependencies
    - cd emgen
    - brew install python3 llvm
    - export LLVM_CONFIG=`find /usr/local/Cellar -name llvm-config`

script:
    - git-dependencies update -r
    - mkdir build && cd build
    - cmake -DLLVM_CONFIG_BINARY=$LLVM_CONFIG ..
    - cmake --build .
